In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [5]:
# write your code here ^_^
x = np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [8]:
# write your code here ^_^
y = np.zeros((2,2))
y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [11]:
# write your code here ^_^
np.add(x,y)

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
# write your code here ^_^
print(f"x array characteristics:\n x dimension:{x.ndim}\n x shape:{x.shape}\n x size:{x.size}")

x array characteristics:
 x dimension:2
 x shape:(2, 2)
 x size:4


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [17]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [20]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [116]:
# write your code here ^_^
z_reshape = z.reshape(1,-1)
newArray = np.hstack((w,z_reshape.T)) # The second argument -1 will automatically determine the number of columns
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [119]:
# write your code here ^_^
for r in newArray:
    for elements in r:
        print(elements)

11
12
1
13
14
2
15
16
3


In [121]:
for r in np.nditer(newArray): #or we can use nditer method to visit every element of an array
    print(r)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [124]:
# write your code here ^_^
newArray.T

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [127]:
# write your code here ^_^
newArray = newArray-1
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [130]:
# write your code here ^_^
print(f"Smallest value = {newArray.min()}\nBiggest value= {newArray.max()}")

Smallest value = 0
Biggest value= 15


## Q#12: Print the first row of "newArray" using indexing.

In [133]:
# write your code here ^_^
newArray[0]

array([10, 11,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [136]:
# write your code here ^_^
newArray[1][1]

13

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [139]:
# write your code here ^_^
print(f"{newArray[0][0]}\n{newArray[1][2]}")

10
1


## Q#15: Change the shape of "newArray" to (9,1).

In [142]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [145]:
# write your code here ^_^
newArray = np.delete(newArray,2,axis=0)
newArray = newArray.reshape(3,2)
newArray

array([[10, 11],
       [ 0, 12],
       [13,  1]])

# Well Done 🎉